### PR TITLE
feat(template): Update with some tweaks

### PR DESCRIPTION
**Pull request by mlissner**

### CODE REVIEW

**Comment by mlissner** [comment]
@s-taube, this is a PR for the changes I'm making to your template. I think they'll make sense as a diff for you if you click the "Files Changed" tab. 

Let me know what you think and if you like it as is, you can hit the Merge button to update the issue template!

**Comment by mlissner** [comment]
PS, I put these on your backlog, so you can get to this when it gets to the top. No big rush. :)

**Comment by s-taube** [comment]
@mlissner I don't think I have permission to merge. Following [these](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request) github instructions, but I don't see a "merge" option. I can "comment" or "close with comment," and I see "only those with write access to this repository can merge pull requests."

**Comment by mlissner** [comment]
Permission should be granted. Sorry about that!

**Pull request merged**
